/*
 * test_golden_vector.c — Golden vector comparison between PyTorch inference output and C engine output
 *
 * Compares streaming STFT + PyTorch model_forward() output
 * generated by scripts/golden_vectors_streaming.py
 * with C engine fe_process() output on a per-frame basis.
 *
 * Both sides use streaming STFT (zero-init overlap), so there is
 * no STFT framing difference; only numerical agreement of the NN pipeline is tested.
 *
 * golden_input.bin / golden_output.bin: raw float32 LE, N_FRAMES * HOP_SIZE floats
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "unity/unity.h"
#include "../../src/engine/exports.h"

#define GOLDEN_N_FRAMES   40
#define GOLDEN_HOP_SIZE   512
#define GOLDEN_N_SAMPLES  (GOLDEN_N_FRAMES * GOLDEN_HOP_SIZE)

#if defined(FE_USE_BASE_48K)
#define GOLDEN_MODEL_ID       FE_MODEL_BASE
#define WEIGHTS_PATH         "weights/fe_base_48k.bin"
#define GOLDEN_INPUT_PATH    "tests/golden_base/golden_input.bin"
#define GOLDEN_OUTPUT_PATH   "tests/golden_base/golden_output.bin"
#elif defined(FE_USE_SMALL_48K)
#define GOLDEN_MODEL_ID       FE_MODEL_SMALL
#define WEIGHTS_PATH         "weights/fe_small_48k.bin"
#define GOLDEN_INPUT_PATH    "tests/golden_small/golden_input.bin"
#define GOLDEN_OUTPUT_PATH   "tests/golden_small/golden_output.bin"
#else
#define GOLDEN_MODEL_ID       FE_MODEL_TINY
#define WEIGHTS_PATH         "weights/fe_tiny_48k.bin"
#define GOLDEN_INPUT_PATH    "tests/golden/golden_input.bin"
#define GOLDEN_OUTPUT_PATH   "tests/golden/golden_output.bin"
#endif

/* Tolerance thresholds: streaming STFT golden (precision limits of float32 NN approximate implementation)
 * MSE: Absolute error between C and PyTorch. Sufficient precision at 1e-10 or below.
 * SNR: Differences between C's polynomial sigmoid approximation vs PyTorch's exact sigmoid,
 *      and C's radix-2 FFT vs library FFT, accumulate through 40 frames of GRU hidden state,
 *      resulting in ~60 dB.
 *      Set to 55 dB (10 dB safety margin). */
#define MSE_THRESHOLD_OVERALL  1.0e-10f
#define MSE_THRESHOLD_STEADY   1.0e-10f  /* frame 5 onwards */
#define SNR_THRESHOLD_DB       55.0f

void setUp(void) {}
void tearDown(void) {}

static uint8_t* read_file_u8(const char* path, int* out_len) {
    FILE* f = fopen(path, "rb");
    if (!f) { *out_len = 0; return NULL; }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    uint8_t* buf = (uint8_t*)malloc((size_t)sz);
    if (buf) {
        size_t rd = fread(buf, 1, (size_t)sz, f);
        *out_len = (int)rd;
    }
    fclose(f);
    return buf;
}

static float* read_file_f32(const char* path, int* out_count) {
    int byte_len = 0;
    uint8_t* raw = read_file_u8(path, &byte_len);
    if (!raw) { *out_count = 0; return NULL; }
    *out_count = byte_len / (int)sizeof(float);
    return (float*)raw;
}

/* Per-frame MSE computation */
static float compute_mse(const float* a, const float* b, int n) {
    double sum = 0.0;
    for (int i = 0; i < n; i++) {
        double d = (double)a[i] - (double)b[i];
        sum += d * d;
    }
    return (float)(sum / n);
}

/* Signal power computation */
static float compute_power(const float* x, int n) {
    double sum = 0.0;
    for (int i = 0; i < n; i++) {
        sum += (double)x[i] * (double)x[i];
    }
    return (float)(sum / n);
}

void test_golden_vector_files_exist(void) {
    int len = 0;
    float* inp = read_file_f32(GOLDEN_INPUT_PATH, &len);
    TEST_ASSERT_NOT_NULL_MESSAGE(inp,
        "golden_input.bin not found. Run scripts/golden_vectors_streaming.py first.");
    TEST_ASSERT_EQUAL_INT_MESSAGE(GOLDEN_N_SAMPLES, len,
        "golden_input.bin sample count does not match expected value");
    free(inp);

    float* out = read_file_f32(GOLDEN_OUTPUT_PATH, &len);
    TEST_ASSERT_NOT_NULL_MESSAGE(out,
        "golden_output.bin not found. Run scripts/golden_vectors_streaming.py first.");
    TEST_ASSERT_EQUAL_INT_MESSAGE(GOLDEN_N_SAMPLES, len,
        "golden_output.bin sample count does not match expected value");
    free(out);
}

void test_golden_vector_comparison(void) {
    /* Load weights */
    int wt_len = 0;
    uint8_t* wt_data = read_file_u8(WEIGHTS_PATH, &wt_len);
    TEST_ASSERT_NOT_NULL_MESSAGE(wt_data, "Weight file not found");

    FeState* state = fe_init(GOLDEN_MODEL_ID, wt_data, wt_len);
    TEST_ASSERT_NOT_NULL_MESSAGE(state, "fe_init failed");

    /* Load golden vectors */
    int inp_count = 0, out_count = 0;
    float* golden_in  = read_file_f32(GOLDEN_INPUT_PATH, &inp_count);
    float* golden_out = read_file_f32(GOLDEN_OUTPUT_PATH, &out_count);
    TEST_ASSERT_NOT_NULL_MESSAGE(golden_in, "Failed to load golden_input.bin");
    TEST_ASSERT_NOT_NULL_MESSAGE(golden_out, "Failed to load golden_output.bin");
    TEST_ASSERT_EQUAL_INT(GOLDEN_N_SAMPLES, inp_count);
    TEST_ASSERT_EQUAL_INT(GOLDEN_N_SAMPLES, out_count);

    /* Process per-frame with C engine */
    float* c_output = (float*)calloc(GOLDEN_N_SAMPLES, sizeof(float));
    TEST_ASSERT_NOT_NULL(c_output);

    float* in_ptr  = fe_get_input_ptr(state);
    float* out_ptr = fe_get_output_ptr(state);
    int hop = fe_get_hop_size(state);
    TEST_ASSERT_EQUAL_INT_MESSAGE(GOLDEN_HOP_SIZE, hop, "hop_size mismatch");

    for (int f = 0; f < GOLDEN_N_FRAMES; f++) {
        memcpy(in_ptr, golden_in + f * hop, sizeof(float) * hop);
        int ret = fe_process(state, in_ptr, out_ptr);
        TEST_ASSERT_EQUAL_INT_MESSAGE(0, ret, "fe_process failed");
        memcpy(c_output + f * hop, out_ptr, sizeof(float) * hop);
    }

    /* === Overall frame comparison === */
    float overall_mse = compute_mse(c_output, golden_out, GOLDEN_N_SAMPLES);
    float ref_power   = compute_power(golden_out, GOLDEN_N_SAMPLES);
    float snr_db      = (ref_power > 1e-20f)
                      ? 10.0f * log10f(ref_power / (overall_mse + 1e-30f))
                      : -999.0f;

    printf("\n=== Golden Vector Comparison Results ===\n");
    printf("Overall MSE:       %.6e\n", overall_mse);
    printf("Reference power:   %.6e\n", ref_power);
    printf("SNR:               %.2f dB\n", snr_db);

    /* === Per-frame comparison === */
    float max_frame_mse = 0.0f;
    float max_steady_mse = 0.0f;
    int worst_frame = 0;
    int worst_steady_frame = 0;

    printf("\nPer-frame MSE (first 10 frames):\n");
    for (int f = 0; f < GOLDEN_N_FRAMES; f++) {
        float fmse = compute_mse(c_output + f * hop, golden_out + f * hop, hop);
        if (f < 10) {
            printf("  Frame %2d: MSE=%.6e\n", f, fmse);
        }
        if (fmse > max_frame_mse) {
            max_frame_mse = fmse;
            worst_frame = f;
        }
        if (f >= 5 && fmse > max_steady_mse) {
            max_steady_mse = fmse;
            worst_steady_frame = f;
        }
    }
    printf("...\n");
    printf("Worst frame:         Frame %d (MSE=%.6e)\n", worst_frame, max_frame_mse);
    printf("Worst steady frame:  Frame %d (MSE=%.6e)\n", worst_steady_frame, max_steady_mse);

    /* === Verify output contains no NaN/Inf values === */
    for (int i = 0; i < GOLDEN_N_SAMPLES; i++) {
        if (c_output[i] != c_output[i] || c_output[i] > 1e30f || c_output[i] < -1e30f) {
            char msg[128];
            snprintf(msg, sizeof(msg), "C output[%d] = %f (NaN/Inf detected)", i, c_output[i]);
            TEST_FAIL_MESSAGE(msg);
        }
    }

    /* === Threshold checks === */
    char msg[256];
    snprintf(msg, sizeof(msg),
        "Overall MSE %.6e > threshold %.6e", overall_mse, MSE_THRESHOLD_OVERALL);
    TEST_ASSERT_TRUE_MESSAGE(overall_mse < MSE_THRESHOLD_OVERALL, msg);

    snprintf(msg, sizeof(msg),
        "Steady-state MSE %.6e > threshold %.6e (worst frame %d)",
        max_steady_mse, MSE_THRESHOLD_STEADY, worst_steady_frame);
    TEST_ASSERT_TRUE_MESSAGE(max_steady_mse < MSE_THRESHOLD_STEADY, msg);

    snprintf(msg, sizeof(msg),
        "SNR %.2f dB < threshold %.2f dB", snr_db, SNR_THRESHOLD_DB);
    TEST_ASSERT_TRUE_MESSAGE(snr_db > SNR_THRESHOLD_DB, msg);

    /* Cleanup */
    free(c_output);
    free(golden_in);
    free(golden_out);
    fe_destroy(state);
    free(wt_data);
}

int main(void) {
    UNITY_BEGIN();
    RUN_TEST(test_golden_vector_files_exist);
    RUN_TEST(test_golden_vector_comparison);
    return UNITY_END();
}
