/**
 * embed-assets.ts — バイナリ資産をTSモジュールに変換するコード生成スクリプト
 *
 * 入力:
 *   dist/wasm/*.wasm          (6ファイル: 3モデル × 2バリアント)
 *   dist/wasm/*-exports.json  (6ファイル)
 *   weights/*.bin             (3ファイル)
 *   src/worklet/processor.js  (1ファイル)
 *
 * 出力:
 *   src/embedded/wasm-{model}-{variant}.ts     (6ファイル)
 *   src/embedded/weights-{model}.ts            (3ファイル)
 *   src/embedded/exports-{model}-{variant}.ts  (6ファイル)
 *   src/embedded/processor-source.ts           (1ファイル)
 *
 * 実行: bun run scripts/embed-assets.ts
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dir, '..');
const DIST_WASM = join(ROOT, 'dist', 'wasm');
const WEIGHTS_DIR = join(ROOT, 'weights');
const PROCESSOR_JS = join(ROOT, 'src', 'worklet', 'processor.js');
const OUTPUT_DIR = join(ROOT, 'src', 'embedded');

const MODELS = ['tiny', 'base', 'small'] as const;
const VARIANTS = ['scalar', 'simd'] as const;

type Model = (typeof MODELS)[number];
type Variant = (typeof VARIANTS)[number];

function toBase64(buf: Buffer): string {
  return buf.toString('base64');
}

function generateWasmModule(model: Model, variant: Variant): string {
  const wasmPath = join(DIST_WASM, `fastenhancer-${model}-${variant}.wasm`);
  if (!existsSync(wasmPath)) {
    throw new Error(`WASM file not found: ${wasmPath}`);
  }
  const buf = readFileSync(wasmPath);
  const b64 = toBase64(buf);
  return `// Auto-generated by scripts/embed-assets.ts — DO NOT EDIT
const _b64 = "${b64}";
let _cached: ArrayBuffer | null = null;
function _decode(): ArrayBuffer {
  if (!_cached) {
    const bin = atob(_b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
    _cached = arr.buffer as ArrayBuffer;
  }
  return _cached;
}
export function getWasmBytes(): ArrayBuffer {
  return _decode().slice(0);
}
`;
}

function generateWeightsModule(model: Model): string {
  const weightPath = join(WEIGHTS_DIR, `fe_${model}_48k.bin`);
  if (!existsSync(weightPath)) {
    throw new Error(`Weight file not found: ${weightPath}`);
  }
  const buf = readFileSync(weightPath);
  const b64 = toBase64(buf);
  return `// Auto-generated by scripts/embed-assets.ts — DO NOT EDIT
const _b64 = "${b64}";
let _cached: ArrayBuffer | null = null;
function _decode(): ArrayBuffer {
  if (!_cached) {
    const bin = atob(_b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
    _cached = arr.buffer as ArrayBuffer;
  }
  return _cached;
}
export function getWeightData(): ArrayBuffer {
  return _decode().slice(0);
}
`;
}

function generateExportsModule(model: Model, variant: Variant): string {
  const exportsPath = join(DIST_WASM, `fastenhancer-${model}-${variant}-exports.json`);
  if (!existsSync(exportsPath)) {
    throw new Error(`Export map not found: ${exportsPath}`);
  }
  let raw = readFileSync(exportsPath, 'utf-8');
  // BOMを除去
  if (raw.charCodeAt(0) === 0xfeff) {
    raw = raw.slice(1);
  }
  const parsed = JSON.parse(raw) as Record<string, string>;
  const entries = Object.entries(parsed)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(',\n');
  return `// Auto-generated by scripts/embed-assets.ts — DO NOT EDIT
export const exportMap: Record<string, string> = {
${entries},
};
`;
}

function generateProcessorSourceModule(): string {
  if (!existsSync(PROCESSOR_JS)) {
    throw new Error(`Processor JS not found: ${PROCESSOR_JS}`);
  }
  const source = readFileSync(PROCESSOR_JS, 'utf-8');
  // テンプレートリテラル内で${}とバッククォートをエスケープ
  const escaped = source
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
  return `// Auto-generated by scripts/embed-assets.ts — DO NOT EDIT
export const processorSource = \`${escaped}\`;
`;
}

function main(): void {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  let fileCount = 0;

  // WASMバイナリ (6ファイル)
  for (const model of MODELS) {
    for (const variant of VARIANTS) {
      const content = generateWasmModule(model, variant);
      const outPath = join(OUTPUT_DIR, `wasm-${model}-${variant}.ts`);
      writeFileSync(outPath, content, 'utf-8');
      const sizeKB = (Buffer.byteLength(content, 'utf-8') / 1024).toFixed(1);
      console.log(`  生成: wasm-${model}-${variant}.ts (${sizeKB}KB)`);
      fileCount++;
    }
  }

  // 重みバイナリ (3ファイル)
  for (const model of MODELS) {
    const content = generateWeightsModule(model);
    const outPath = join(OUTPUT_DIR, `weights-${model}.ts`);
    writeFileSync(outPath, content, 'utf-8');
    const sizeKB = (Buffer.byteLength(content, 'utf-8') / 1024).toFixed(1);
    console.log(`  生成: weights-${model}.ts (${sizeKB}KB)`);
    fileCount++;
  }

  // エクスポートマップ (6ファイル)
  for (const model of MODELS) {
    for (const variant of VARIANTS) {
      const content = generateExportsModule(model, variant);
      const outPath = join(OUTPUT_DIR, `exports-${model}-${variant}.ts`);
      writeFileSync(outPath, content, 'utf-8');
      const sizeKB = (Buffer.byteLength(content, 'utf-8') / 1024).toFixed(1);
      console.log(`  生成: exports-${model}-${variant}.ts (${sizeKB}KB)`);
      fileCount++;
    }
  }

  // processor.js ソース (1ファイル)
  const processorContent = generateProcessorSourceModule();
  const processorOutPath = join(OUTPUT_DIR, 'processor-source.ts');
  writeFileSync(processorOutPath, processorContent, 'utf-8');
  const sizeKB = (Buffer.byteLength(processorContent, 'utf-8') / 1024).toFixed(1);
  console.log(`  生成: processor-source.ts (${sizeKB}KB)`);
  fileCount++;

  console.log(`\n完了: ${fileCount}ファイルを ${OUTPUT_DIR} に生成しました。`);
}

main();
